// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55ovuAazO3Rd8KtM5a4R1XBlQG_8n870',
    appId: '1:781128513492:web:57fbdefafc2bb219b58841',
    messagingSenderId: '781128513492',
    projectId: 'resumemaker-a298f',
    authDomain: 'resumemaker-a298f.firebaseapp.com',
    storageBucket: 'resumemaker-a298f.firebasestorage.app',
    measurementId: 'G-JBQW4KPMWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXNuypPE_3i0nKCRu1E-pQ6zu8NVnkRKk',
    appId: '1:781128513492:android:6b50ad159c8c40f9b58841',
    messagingSenderId: '781128513492',
    projectId: 'resumemaker-a298f',
    storageBucket: 'resumemaker-a298f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-94nVDoXSApeoXBrW_4UKitBoPCP0IO0',
    appId: '1:781128513492:ios:4976b5c92e6d4ed6b58841',
    messagingSenderId: '781128513492',
    projectId: 'resumemaker-a298f',
    storageBucket: 'resumemaker-a298f.firebasestorage.app',
    iosBundleId: 'com.example.resumeMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-94nVDoXSApeoXBrW_4UKitBoPCP0IO0',
    appId: '1:781128513492:ios:4976b5c92e6d4ed6b58841',
    messagingSenderId: '781128513492',
    projectId: 'resumemaker-a298f',
    storageBucket: 'resumemaker-a298f.firebasestorage.app',
    iosBundleId: 'com.example.resumeMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA55ovuAazO3Rd8KtM5a4R1XBlQG_8n870',
    appId: '1:781128513492:web:40585d72f86da35fb58841',
    messagingSenderId: '781128513492',
    projectId: 'resumemaker-a298f',
    authDomain: 'resumemaker-a298f.firebaseapp.com',
    storageBucket: 'resumemaker-a298f.firebasestorage.app',
    measurementId: 'G-1Z8SM69VY4',
  );
}
